#!/bin/python3

import sys

def insertionSort1(n, arr):
    
    #convert to integers
    numbers = [int(x) for x in arr]
    
    #check if array is intially sorted
    check = all(numbers[i] <= numbers[i+1] for i in range(len(numbers) - 1))
    
    #get the number last number in the array
    l = len(numbers)
    unsorted_number = numbers[l-1]
    
    #keep looping until array is sorted
    while check == False:
        for i in range(l-1):   
            if unsorted_number < numbers[l-(i+2)]:
                numbers[l-(i+1)] = numbers[l-(i+2)]
                last_index = l-(i+2)
                print(' '.join(map(str, numbers)))
                
        check = all(numbers[i] <= numbers[i+1] for i in range(len(numbers) - 1))
    
    #swap out last number
    numbers[last_index] = unsorted_number
    print(' '.join(map(str, numbers)))   

if __name__ == "__main__":
    n = int(input().strip())
    arr = list(map(int, input().strip().split(' ')))
    insertionSort1(n, arr)
